---
name: Build

on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
    branches:
      - main
  schedule:
    # We want to run right after the `latest` image is published.
    # So, let's do it an hour right after. Look the schedule of publishing here:
    # https://github.com/alexhumphreys/idris2-dockerfile/blob/main/.github/workflows/docker-image.yml
    - cron: '0 1 * * *'

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build ${{ github.repository }} with Idris2 latest
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    container: snazzybucket/idris2api:latest
    steps:
      - name: Checkout tailrec
        uses: actions/checkout@v2
        with:
          repository: stefan-hoeck/idris2-tailrec
      - name: Install tailrec
        run: make install
      - name: Checkout freer
        uses: actions/checkout@v2
        with:
          repository: stefan-hoeck/idris2-freer
      - name: Install freer
        run: make install
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build lib
        run: make lib
